export const DEPARTMENTS = [
  'Capacitor',
  'Coil Auto',
  'Resistor',
  'Management Office',
  'Production Engineering',
  'Mechanical Equipment Group',
  'Finance',
  'Quality Innovation',
  'Environment Health and Safety',
  'Human Resources',
  'Procurement and Logistic',
  'Facilities and General Affairs',
  'Information System',
]
