export const GRADES = [
  { step: 1, title: 'Operator', project: false, toeic: false },
  { step: 2, title: 'Senior Operator C', project: false, toeic: false },
  { step: 3, title: 'Senior Operator B', project: false, toeic: false },
  { step: 4, title: 'Senior Operator A', project: false, toeic: false },
  { step: 5, title: 'Junior Staff 1', project: true, toeic: false },
  { step: 6, title: 'Junior Staff 2', project: false, toeic: false },
  { step: 7, title: 'Staff 1', project: true, toeic: false },
  { step: 8, title: 'Staff 2', project: true, toeic: false },
  { step: 9, title: 'Staff 3', project: false, toeic: false },
  { step: 10, title: 'Senior Staff 1', project: true, toeic: true },
  { step: 11, title: 'Senior Staff 2', project: false, toeic: true },
  { step: 12, title: 'Executive', project: true, toeic: true },
  { step: 13, title: 'Senior Executive', project: false, toeic: true },
  { step: 14, title: 'Manager 1', project: true, toeic: true },
  { step: 15, title: 'Manager 2', project: true, toeic: true },
  { step: 16, title: 'Senior Manager', project: true, toeic: true },
  { step: 17, title: 'Assistant General Manager', project: true, toeic: true },
  { step: 18, title: 'General Manager', project: true, toeic: true },
]
